version: "3.9"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
    task-manager:
        image: gimmitest/task-manager
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DEFAULT_PORT: 3000
        container_name: taskapi
        environment:
            PORT: 3000
            MONGO_URL: host.docker.internal:27017
        ports:
            - 3000:3000
        depends_on:
            - mongodb
