apiVersion: v1
kind: Service
metadata:
    name: mongo-service
spec:
    selector:
        app: mongo
    ports:
        - port: 27017
          targetPort: 27017
          protocol: TCP
    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    name: task-service
spec:
    selector:
        app: task-manager
    ports:
        - port: 3000
          targetPort: 3000
          protocol: TCP
    type: NodePort
